config/routes.rb
CuratorRailsExample::Application.routes.draw do
  resources :notes
  root :to => 'notes#index'

end

app/models/note.rb
class Note
  include Curator::Model
  include ActiveModel::Validations
  attr_accessor :id, :title, :description, :user_id

  validates :title, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/notes_controller.rb
class NotesController < ActionController::Base
  USER_ID = 1

  def index
    @notes = NoteRepository.find_by_user_id(USER_ID)
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(request.POST[:note].merge(:user_id => USER_ID))
    if @note.valid?
      NoteRepository.save(@note)
      redirect_to notes_path
    else
      render :new
    end
  end

  def show
    @note = NoteRepository.find_by_id(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CuratorRailsExample</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notes/index.html.erb
<h1>Notes</h1>

<ul>
  <% @notes.each do |note| -%>
    <li><%= link_to note.title, note_path(note) %></li>
  <% end -%>
</ul>

<%= link_to "New Note", new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>
<%= form_for @note do |f| %>
  <%= f.error_messages %>
  <dl>
    <dt><%= f.label :title %></dt>
    <dd><%= f.text_field :title %></dd>
    <dt><%= f.label :description %></dt>
    <dd><%= f.text_area :description, :size => "60x12" %></dd>
    <p>If you create the note at version 0, it will run through migration 1 the next time it is read. If you create it at version 1, no migrations will run.</p>
    <dt><%= f.label :version %></dt>
    <dd><%= f.select :version, :options => [0, 1] %></dd>
  </dl>
  <%= f.submit "Create" %>
<% end %>

app/views/notes/show.html.erb
<h1>Note</h1>

<div>Id: <%= @note.id %></div>
<div>Title: <%= @note.title %></div>
<div>Description: <%= @note.description %></div>

<%= link_to "Back to index", notes_path %>